version: '3'
services: 
    server:
        container_name: node-docker
        restart: always
        build: .
        command: npm start
        ports: 
            - '5000:5000'
        links: 
            - 'mongo'
    mongo:
        container_name: mongo
        image: mongo
        volumes:
            - localstore:/data/db
volumes:
    localstore: